parameters:
#    zabbix_reports_main.example.class: ZabbixReports\MainBundle\Example


services:

    zabbix_api:
        class: ZabbixReports\MainBundle\ZabbixApi\ZabbixApi
        arguments: ['@logger', %zbx_url%, %zbx_username%, %zbx_password% ]
        
#    zabbix_reports_main.example:
#        class: %zabbix_reports_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    zabbixreports.twig.zabbix_extension:
        class: ZabbixReports\MainBundle\Twig\ZabbixExtension
        arguments: ['@service_container', '@logger', '@zabbix_api' ]
        tags:
          - { name: twig.extension }

    error_handler:
        class: ZabbixReports\MainBundle\Twig\ErrorEventListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
