parameters:
#    zabbix_reports_main.example.class: ZabbixReports\MainBundle\Example

services:
#    zabbix_reports_main.example:
#        class: %zabbix_reports_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
