parameters:
#    zabbix_reports_main.example.class: ZabbixReports\MainBundle\Example


services:

    zabbix_api:
        class: ZabbixReports\MainBundle\ZabbixApi\ZabbixApi
        arguments: ['@logger', '@zbx_cache', %zbx_url%, %zbx_username%, %zbx_password% ]
        
    zabbixreports.twig.zbx_api_extension:
        class: ZabbixReports\MainBundle\Twig\ZbxApiExtension
        arguments: ['@service_container', '@logger', '@zabbix_api' ]
        tags:
          - { name: twig.extension }

    zabbixreports.twig.zbx_graph_extension:
        class: ZabbixReports\MainBundle\Twig\ZbxGraphExtension
        arguments: ['@service_container', '@logger', '@zabbix_api' ]
        tags:
          - { name: twig.extension }

    zabbixreports.twig.zbx_service_extension:
        class: ZabbixReports\MainBundle\Twig\ZbxServiceExtension
        arguments: ['@service_container', '@logger', '@zabbix_api' ]
        tags:
          - { name: twig.extension }

    zabbixreports.twig.zbx_util_extension:
        class: ZabbixReports\MainBundle\Twig\ZbxUtilExtension
        arguments: ['@service_container', '@logger', '@zabbix_api' ]
        tags:
          - { name: twig.extension }

    zabbixreports.twig.zbx_period_extension:
        class: ZabbixReports\MainBundle\Twig\ZbxPeriodExtension
        arguments: ['@service_container', '@logger', '@zabbix_api' ]
        tags:
          - { name: twig.extension }

    zabbixreports.twig.zbx_stats_extension:
        class: ZabbixReports\MainBundle\Twig\ZbxStatsExtension
        arguments: ['@service_container', '@logger', '@zabbix_api' ]
        tags:
          - { name: twig.extension }

    zbx_cache:
        class: ZabbixReports\MainBundle\Cache\ZbxCache
        arguments: ['@service_container', '@logger' ]

    error_handler:
        class: ZabbixReports\MainBundle\Twig\ErrorEventListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
